CONFIG_OPTS = {
    "lut=n": "",
    "lut=y": "LUT",
    "char_with_sign_is_glyph=n": "",
    "char_with_sign_is_glyph=y": "CHAR_WITH_SIGN_IS_GLYPH",
    "lut=n": "",
    "lut=y": "LUT",
    "bitset=n": "",
    "bitset=y": "BITSET",
    "float=n": "",
    "float=y": "FLOAT",
    "complex=n": "",
    "complex=y": "COMPLEX",
    "splice=n": "",
    "splice=y": "SPLICE",
    "interactive=n": "",
    "interactive=y": "INTERACTIVE",
    "stdin_eof=n": "",
    "stdin_eof=y": "STDIN_EOF",
    "late_binding=n": "",
    "late_binding=y": "LATE_BINDING",
    "cerr=n": "",
    "cerr=y": "CERR",
    "large_output=n": "",
    "large_output=y": "LARGE_OUTPUT",
}

ARCHITECTURES = {
    "x86_64": ["sse4.1", "avx2"],
    "aarch64": ["neon"],
}
